name: Deploy to SEOhost

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Wiadomość opisująca deployment'
        required: true
        default: 'Manual deployment'

# Disable GitHub Pages deployment
permissions:
  contents: read
  pages: none

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Echo deploy message
        run: echo "Deploying to tatrzanski-quiz.pnytko.pl"
      
      - name: List files to deploy
        run: |
          echo "Files to deploy:"
          ls -la
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: h22.seohost.pl
          username: srv41873
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/tatrzanski-quiz.pnytko.pl/public_html/
          dangerous-clean-slate: true
          dry-run: false
          log-level: verbose
